# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux

julia:
  - 1.3

script:
  - julia --color=yes --project -e 'using Pkg; pkg"dev Bukdu"'
  - julia --color=yes --project -e 'using Pkg; pkg"instantiate"; pkg"precompile"; Pkg.test(coverage=true)'
